<?php
use MapasCulturais\i;

return array(
    1 => array(
        'slug' => 'tag',
        'description' => i::__('Tag'),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        'slug' => 'area',
        'description' => i::__('Área de Atuação'),
        'required' => i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
            i::__('Auditor Ambiental'),
            i::__('Antropologia'),
            i::__('Arqueologia'),
            i::__('Arquitetura-Urbanismo'),
            i::__('Biogeografia'),
            i::__('Biológo'),
            i::__('Bioquimico'),
            i::__('Biotecnologia'),
            i::__('Artesanato'),
            i::__('Audiovisual'),
            i::__('Cinema'),
            i::__('Biotecnólogo'),
            i::__('Comunicação'),
            i::__('Botanico'),
            i::__('Cartografia'),
            i::__('Catador'),
            i::__('Ciência Florestal'),
            i::__('Climatologista'),
            i::__('Contador Ambiental'),
            i::__('Designer de Produtos Sustentáveis'),
            i::__('Direito Ambiental'),
            i::__('Ecologia'),
            i::__('Ecoturismo'),
            i::__('Educação Ambiental'),
            i::__('Engenharia Agrícola'),
            i::__('Engenharia Florestal'),
            i::__('Filosofia'),
            i::__('Fotografia'),
            i::__('Gastronomia'),
            i::__('Engenharia Hídrica'),
            i::__('História'),
            i::__('Engenharia de Energia'),
            i::__('Jornalismo'),
            i::__('Engenheiro de Pesca'),
            i::__('Literatura'),
            i::__('Engenheiro sanitarista'),
            i::__('Meio Ambiente'),
            i::__('Mídias Sociais'),
            i::__('Moda'),
            i::__('Museu'),
            i::__('Especialista em Gestão de Resíduos'),
            i::__('Novas Mídias'),
            i::__('Estagiário'),
            i::__('Geografia'),
            i::__('Geologia'),
            i::__('Geomorfologia'),
            i::__('Geoprocessamento'),
            i::__('Gestão Ambiental'),
            i::__('Guia turístico'),
            i::__('Indigena'),
            i::__('Sociologia'),
            i::__('Teatro'),
            i::__('Mateiro'),
            i::__('Metereologia'),
            i::__('Oceanografia'),
            i::__('Pedológo'),
            i::__('Pescador'),
            i::__('Pesquisador'),
            i::__('Quilombola'),
            i::__('Ribeirinho'),
            i::__('Topografia'),
            i::__('Turismo de aventura'),
            i::__('Turismo natural'),
            i::__('Veterinário'),
            i::__('Zootécnia'),
            i::__('Outros')
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'description' => i::__('Tipo do evento'),
        'required' => i::__("Você precisa informar o tipo do evento"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
            i::__('Acadêmico'),
            i::__('Ativista'),
            i::__('Cultural'),
            i::__('Esportivo'),
            i::__('Audiovisual'),
            i::__('Teatral'),
            i::__('Político'),
            i::__('Ecológico'),
            i::__('Ambiental'),
            i::__('Dança'),
            i::__('Exposição'),
            i::__('Festa'),
            i::__('Literário'),
            i::__('Músical'),
            i::__('excursão'),
            i::__('Palestra, Debate ou Encontro'),
            i::__('simpósio'),
            i::__('Cimeira'),
            i::__('Outros')
        )
    ),
    4 => array(
        'slug' => 'funcao',
        'description' => i::__('Função'),
        'entities' => array(
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
            i::__("Aderecista"),
            i::__("Adestrador(a)"),
            i::__("Assessor(a) de Comunicação"),
            i::__("Assistente Administrativo"),
            i::__("Assistente de Maquinaria"),
            i::__("Assistente de Montagem"),
            i::__("Assistente de Objetos"),
            i::__("Assistente de Roteiro"),
            i::__("Assistente de Transporte"),
            i::__("Consultor(a) em Audiodescrição"),
            i::__("Consultor(a) em Braille"),
            i::__("Consultor(a) em Libras"),
            i::__("Diagramador(a)"),
            i::__("Digitalizador(a)"),
            i::__("Editor(a)"),
            i::__("Eletricista"),
            i::__("Guia-intérprete de língua de sinais"),
            i::__("Legendista ou Tradutor(a)"),
            i::__("Motorista"),
            i::__("Músico-Musicista"),
            i::__("Outra função técnica"),
            i::__("Radialista"),
            i::__("Sapateiro"),
            i::__("Serigrafista"),
            i::__("Técnico de Luz"),
            i::__("Técnico(a) Contábil"),
            i::__("Técnico(a) de Som"),
            i::__("Tradutor(a) ou Intérprete de Libras"),
            i::__("Transcritor ou Revisor em Braille"),
                        
        )
    )
);
